--- 
:backgroundrb: 
  :ip: 0.0.0.0
  :port: 11007
:schedules:
  :event_collector_worker:
    :run:
      :trigger_args: */10 * * * * *
  :notifier_worker:
    :send_out_emails:
      :trigger_args: */10 * * * * *